print('Enter the name of the Cat 1:')
catName1 = input()
print('Enter the name of the Cat 2:')
catName2 = input()
print('Enter the name of the Cat 3:')
catName3 = input()
print('Enter the name of the Cat 4:')
catName4 = input()
print('Enter the name of the Cat 5:')
catName5 = input()
print('Enter the name of the Cat 6:')
catName6 = input()

print('The cat name are :')
print(catName1 + ' ' + catName2 + ' ' + catName3 + ' ' + catName4 + ' ' + catName5 + ' ' + catName6)
